### ISSUE TITLE
[Raincoat] Boss Shop Drop Not Functioning w/ Sacrifice Artifact

### ISSUE THREAD

**Issue by imakunee** [Jarlyk/JarlykMods#34]
**Expected Behavior**
When defeating a boss with the Sacrifice artifact activated and boss shop drops enabled, a shop will drop for each player currently playing.

**Current Behavior**
No items or shops drop at all upon defeating a boss with the Artifact of Sacrifice enabled and boss shop drops enabled.

**Comment by Jarlyk** [comment]
So, the reason this is happening is that RoR2 implements the Sacrifice artifact by intercepting any attempt to create an interactable (like a chest or shop) and then prevents it from spawning.  Since the boss shop dropping tries to create shops, the spawn attempts are prevented by the artifact.  This is actually rather tricky to solve in a way that doesn't break the Sacrifice artifact; will need to think about how this might be approached.

**Comment by imakunee** [comment]
Thank you for your quick response and great work on your mods! I look forward to some type of fix as I'm a big fan of both the sacrifice artifact and the artifact of merch. Forgive my naivety in a possible suggestion but perhaps you can drop an item pickup similar to the ones from artifact of command, where you open a dialogue screen with item options, and limit the options available to 3 randomly chosen, similarly to a shop?

**Comment by Jarlyk** [comment]
This should be fixed in 1.0.4
