### ISSUE TITLE
[Hailstorm] Dark Elites darkness is persistent and elites only glow if you are very close, otherwise they are just as dark as their darkness (aka invisible)

### ISSUE THREAD

**Issue by saianna** [Jarlyk/JarlykMods#35]
As title. Looking away does nothing to improve visibility and they pretty much ruin the game if you encounter one of them in a map with plenty of levels/platforms (sky meadow), cause to find it you first have to be close. If you won't be lucky to be close enough you will never spot Dark elite as it doesn't glow purple unless you are in its vicinity.

Suggestion: Rather than cursing us with darkness debuff, what if they instead cast huge field of darkness around themselves. Something like celestial elites. And then just change their colour to white and make them immune to darkness themselves, so players cans till spot them and kill them.

That, or make darkness debuff timed.
Edit: typos

**Comment by Jarlyk** [comment]
I don't plan to make major changes to Dark elites (though might try to make them show through the darkness from a bit further away), but FYI you can disable dark elites in the config file.  The config file can be found under BepInEx\config\com.jarlyk.hailstorm.cfg and the relevant parameter is "EnableDarkElites".  Set that to false and no more Dark elites will spawn.

**Comment by Jarlyk** [comment]
Though, actually, one thing I could do is make the baseline distance for the darkness horizon scale based on the distance to the elite.  If the elite is still very far away, the darkness could also be fairly far out.  This would make dark elites spawning a long distance away less annoying and also give you a sense of how close they are.

**Comment by saianna** [comment]
Any positive change is welcome :)

**Comment by Jarlyk** [comment]
In 1.2.0, the Darkness shader has been improved and when Dark elites are far away, the darkness is significantly less intense, not just in terms of the distance, but in terms of only dimming the background instead of making it pitch black.   Not sure why the purple isn't showing through the dark like it used to, but with the current setup, it should be less of an issue.  Will still look into the purple, as that's supposed to be a clear tell in the darkness.
