### ISSUE TITLE
NRE spam and boss spawning bug

### ISSUE THREAD

**Issue by breadguyyy** [Jarlyk/JarlykMods#59]
When mob cap is full, activating the teleporter will not spawn the boss until an enemy is killed and will spam NREs multiple times a second until then.
Log: https://hastebin.com/emuvamapaw.yaml
spam starts at like 2104, I cut out about 30k lines of it

**Comment by Jarlyk** [comment]
I haven't had a chance to update any mods for the latest patch; I probably won't get to this for a few weeks at least.  For now I recommend removing Hailstorm and EliteSpawningOverhaul.  It's possible this issue is caused by an interaction with some other mod, as well, though it's hard to tell, as there are a lot of mods running here.  If it is, the likely culprit is "ItemDropAPIFixes".

**Comment by breadguyyy** [comment]
yeah i tested without itemdropapifixes (which was also broken by the patch) and it still was happening. this is just an old log that i had saved with some other bugs i've reported. also yeah i had a feeling you were busy rn, just figured id put this on the github for organizations sake. thanks for responding, cheers!

**Comment by Jarlyk** [comment]
Also received report that Hailstorm is possibly allocating quite a bit of memory; might be connected to the NRE spam.  Noting here for future reference when I make time to look at this.

**Comment by Jarlyk** [comment]
Was unable to replicate the NREs; will wait for further feedback now that I've rebuilt in latest patch, as it might be an interaction with some other mod
